# Generated by Django 4.0.3 on 2022-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('CU', 'Customer'), ('MM', 'Merchant Manager'), ('GM', 'Group Manager'), ('SU', 'Super User')], default='CU', max_length=5)),
                ('state', models.JSONField(blank=True, null=True)),
                ('last_login', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
