# Generated by Django 4.0.3 on 2022-04-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buzzr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_points', models.BigIntegerField()),
                ('date_joined', models.DateTimeField()),
                ('birthday', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'Undefined')], default='NA', max_length=2)),
                ('country_code', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField()),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buzzr.user')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uen', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('district', models.IntegerField()),
                ('date_joined', models.DateField()),
                ('type', models.CharField(choices=[('HAW', 'Hawker'), ('RES', 'Restaurant'), ('HOT', 'Hotel'), ('UND', 'Undefined')], default='UND', max_length=3)),
                ('cuisine', models.CharField(choices=[('CHI', 'Chinese'), ('IND', 'Indian'), ('MALAY', 'Malay'), ('WEST', 'Western'), ('VEG', 'Vegetarian'), ('DRINKS', 'DRINKS'), ('NIL', 'UNDEFINED')], default='NIL', max_length=50)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buzzr.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('points', models.IntegerField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting for confirmation from <django.db.models.fields.related.ForeignKey>.'), ('Queuing', 'Order placed.'), ('Preparing', 'Restaurant is preparing.'), ('Ready', 'Ready for collection.')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Buzzr.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Buzzr.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buzzr.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('availability', models.CharField(choices=[('ON', 'Available'), ('OFF', 'Not Available')], default='OFF', max_length=128)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buzzr.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buzzr.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buzzr.food')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buzzr.order'),
        ),
    ]
