# Generated by Django 4.0.3 on 2022-08-07 07:46

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Buzzr', '0002_cart_customer_merchant_order_merchantschedule_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='block',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='merchant',
            name='operation_status',
            field=models.CharField(default='TEMP', max_length=255),
        ),
        migrations.AddField(
            model_name='merchant',
            name='street',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='merchant',
            name='unit',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='cuisine',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CHI', 'Chinese'), ('IND', 'Indian'), ('MALAY', 'Malay'), ('WEST', 'Western'), ('VEG', 'Vegetarian'), ('DRINKS', 'DRINKS'), ('FUSION', 'FUSION'), ('NIL', 'UNDEFINED')], max_length=6),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='type',
            field=models.CharField(choices=[('HAW', 'Hawker'), ('HOT', 'Restaurant'), ('RES', 'Hotel'), ('UND', 'UNDEFINED')], default='UND', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Buzzr.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
