# Generated by Django 4.0.3 on 2022-08-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buzzr', '0003_merchant_block_merchant_operation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='user_type',
        ),
    ]
