# Generated by Django 4.0.3 on 2022-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buzzr', '0004_remove_merchant_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting for confirmation from <django.db.models.fields.related.ForeignKey>.'), ('Queuing', 'Order placed.'), ('Preparing', 'Restaurant is preparing.'), ('Ready', 'Ready for collection.'), ('Cancel', 'Order cancelled.'), ('Complete', 'Order completed.')], max_length=50),
        ),
    ]
